### ISSUE TITLE
Consider support to recognize repo's language to decide which editor to open

### ISSUE THREAD

**Issue by Dentrax** [Jarred-Sumner/git-peek#10]
Thanks for such a cool project!

I.E.:
- Rust: `emacs`
- Go: `goland`
- Java: `intellij`
- CPP: `vim`

But this feature should not break editor search order of course, as described in `help` command: `By default, it will search $EDITOR. If not found, it will try code, then subl, then vim.` i.e.: search order: `goland` -> `vim` -> `subl`

My current workaround is that I currently take a look at what language is used and set a custom `$EDITOR` variable just before `peek` it: `EDITOR=clion git peek https://github.com/ylukem/pin-go`

**Comment by Jarred-Sumner** [comment]
I honestly can’t think of a simple way to make this work. So I’m going to close this as not something that will be added, but if more people ask for it, I’ll consider it
