### ISSUE TITLE
Pre-compiled `brew/git-peek` bloats the repository unnecessarily

### ISSUE THREAD

**Issue by dscho** [Jarred-Sumner/git-peek#11]
Cloning _this_ repository is pretty expensive. [`git sizer`](https://github.com/github/git-sizer) says this:

```
$ git sizer
Processing blobs: 165
Processing trees: 121
Processing commits: 62
Matching commits to trees: 62
Processing annotated tags: 10
Processing references: 13
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Biggest objects              |           |                                |
| * Blobs                      |           |                                |
|   * Maximum size         [1] |  74.1 MiB | *******                        |

[1]  cb3591f1d9a97e7f816927a30e91c101c484091d (refs/heads/main:brew/git-peek)
```

A 74.1 megabyte blob... Unfortunately, this is now part of tagged releases, so it cannot easily be removed. But maybe it can be deleted from the tip revision, and a `.gitignore` could be installed to prevent it from being added again (I see that https://github.com/Jarred-Sumner/git-peek/commit/bbe4e91504346a40033a107cb23c3a906c860d78 tried to delete it but it came back nevertheless)?

**Comment by Jarred-Sumner** [comment]
Yeah...I didn’t mean to commit this.

I suppose I could just delete the git history by resetting and force pushing

**Comment by Jarred-Sumner** [comment]
I ran https://rtyley.github.io/bfg-repo-cleaner/ and now `git sizer` shows:
```bash
❯ git sizer                                                         
Processing blobs: 165
Processing trees: 121
Processing commits: 62
Matching commits to trees: 62
Processing annotated tags: 10
Processing references: 13
No problems above the current threshold were found
```

Thanks for flagging
