### ISSUE TITLE
[WSL] - Doesn't work with code-insiders

### ISSUE THREAD

**Issue by jasonwilliams** [Jarred-Sumner/git-peek#16]
Hey great project

I just tried it out on WSL. I have code-insiders but it doesn't find it sadly.
```
➜  ~ which code-insiders
/mnt/c/Program Files/Microsoft VS Code Insiders/bin/code-insiders
```

```
➜  ~ git peek https://github.com/Jarred-Sumner/git-peek
⏳ Extracting repository to temp folder...
💿 Finished downloading repository!
💻 Launched editor in 1.09s
🗑  Deleted temp repo
```
The above opens Vim.
code-insiders is on my path so im not sure why it doesn't open it up. Im assuming its a WSL issue

Edit:
passing `-e code-insiders works`, is there a way to set that as the default?

Is there a reason why `code` is before `vim` but `code-insiders` is after? I would expect `code-insiders` to also be near the front. https://github.com/Jarred-Sumner/git-peek/blob/main/src/index.ts#L15
I can see you made a concious choice to push it to the end here: https://github.com/Jarred-Sumner/git-peek/commit/8fa612e23a23b88fa393e869bceadcba3177884b but this means it will never get picked on WSL because vim will always exist before it. Unless the user sets `$EDITOR`

**Comment by Jarred-Sumner** [comment]
Is your $EDITOR set to code-insiders? $EDITOR is supposed to automatically handle this, that list is only there for when it can’t use $EDITOR 

Its very subjective what the order should be, but vim/vi should probably be at the end. I didn’t realize how many people run code-insiders instead of the stable version

**Comment by Jarred-Sumner** [comment]
I moved `code-insiders` in front of `$EDITOR`

**Comment by jasonwilliams** [comment]
@Jarred-Sumner my apologies I realised now that zsh pre-set my $EDITOR to “vim” and I’m assuming that’s what the problem was.  I thought the issue was the ordering but git peek was reading the env var

**Comment by jasonwilliams** [comment]
> I moved `code-insiders` in front of `$EDITOR`

I’m ok if you want to revert this, a users choice should probably be first priority. My issue was more vim being chosen ahead of code-insiders when no $EDITOR is set

**Comment by Jarred-Sumner** [comment]
I misspoke - I meant I moved it in front of `vim`

If you have `code-insiders` installed, probably less likely to want to use vim anyway
