### ISSUE TITLE
improve error message for unsupported EDITOR

### ISSUE THREAD

**Issue by AndrewSB** [Jarred-Sumner/git-peek#21]
track something to improve error messaging for unsupported `$EDITOR`s? `nvim` isn't supported right now, and it isn't clear at all that it doesn't work

<img width="505" alt="Screen Shot 2021-02-16 at 12 27 50 PM" src="https://user-images.githubusercontent.com/3814772/108117881-650e5780-7052-11eb-8441-7e35e6763d5b.png">

**Comment by Jarred-Sumner** [comment]
Hmmmm

Try running `git peek nextcloud/ios -e nvim`

Does `nvim` open directly in the terminal for you or does it open in a separate app? Right now, the code assumes any `vi`* will open in the terminal

**Comment by Jarred-Sumner** [comment]
There's a difficult to reproduce issue where the $EDITOR var when set from the shell (i.e. not `~/.git-peek`) is not propagating to `git-peek`'s node.js instance and I'm not sure why.

**Comment by Jarred-Sumner** [comment]
`nvim` is now fixed (as of v1.3.17) and fixed a related bug with detecting the editor
