### ISSUE TITLE
Feature Request: Open pull request in editor

### ISSUE THREAD

**Issue by rushi** [Jarred-Sumner/git-peek#6]
I'd like to be able to open a pull request in my editor using `git peek -e code https://github.com/facebook/react/pull/20790`

**Reason:** When I'm doing code reviews sometimes it's easier to review the code in my editor and be able to jump around the code without using Github's diff UI.

**Additional info:**
If you goto the above PR, fetch the last commit, then the archive should be available here `https://github.com/facebook/react/archive/34501538a866d51f9ec5a486be8d34f8162ccf7f.zip`

**Comment by Jarred-Sumner** [comment]
Added in `1.1.22`!
