### ISSUE TITLE
[Feature Request] Configurable temp path

### ISSUE THREAD

**Issue by ghost** [Jarred-Sumner/git-peek#8]
Great piece of software, just played with it a bit. Although git-peek nicely cleans up after closing the editor, there's _potential_ for bringing a system down by saving to /tmp by default. On most Linux systems /tmp is mounted as tmpfs, meaning that whatever is dropped there, even temporarily, eats into RAM.

I realize that this doesn't pose (much) problems with relatively small repositories, but I wonder if there's some kind of `size limit check` before committing to download a huge repo. For example, what if one wants to take a quick peek at what Linus Torvalds is doing in the [Linux kernel repo](https://github.com/torvalds/linux) (+4GB)? To avoid this _potential_ pitfall it would be nice to have a user-configurable knob to store temporary files at a different location.

**Comment by Jarred-Sumner** [comment]
Added in 1.1.27!
